import XCTest
@testable import RoadStationCore

final class SpiralGeometryTests: XCTestCase {
    func testStart() throws {
        let s = try TestSupport.spiral(); TestSupport.assertPoint(try s.point(at: 0), 0, 0)
        XCTAssertEqual(s.heading(at: 0), 0, accuracy: 1e-12)
    }
    // Independent Fresnel power series values, not generated by this engine.
    func testMidpointIndependentFresnelBenchmark() throws {
        let s = try TestSupport.spiral()
        TestSupport.assertPoint(try s.point(at: 50), 49.980472281808716, 1.0413760591870398, accuracy: 1e-10)
        XCTAssertEqual(s.heading(at: 50), 0.0625, accuracy: 1e-12)
    }
    func testEndpointIndependentFresnelBenchmark() throws {
        let s = try TestSupport.spiral()
        TestSupport.assertPoint(s.end, 99.3768058429589, 8.2962048537095, accuracy: 1e-10)
        XCTAssertEqual(s.heading(at: 100), 0.25, accuracy: 1e-12)
    }
    func testDecreasingCurvature() throws {
        let s = try TestSupport.spiral(decreasing: true)
        // Reversal identity from entry spiral, rotated by theta(L).
        let entry = try TestSupport.spiral(); let x = cos(0.25) * entry.end.x + sin(0.25) * entry.end.y
        let y = sin(0.25) * entry.end.x - cos(0.25) * entry.end.y
        TestSupport.assertPoint(s.end, x, y, accuracy: 1e-9)
        XCTAssertEqual(s.heading(at: 50), 0.1875, accuracy: 1e-12)
    }
    func testClockwiseReflection() throws {
        let a = try TestSupport.spiral(); let b = try TestSupport.spiral(clockwise: true)
        TestSupport.assertPoint(b.end, a.end.x, -a.end.y)
    }
    func testFiniteToFiniteCurvature() throws {
        let s = try SpiralSegment(start: .init(x: 0, y: 0), length: 100, startHeading: 0.3, startCurvature: 0.002, endCurvature: 0.005)
        XCTAssertEqual(s.heading(at: 100), 0.65, accuracy: 1e-12)
        XCTAssertEqual(s.heading(at: 50), 0.4375, accuracy: 1e-12)
    }
    func testZeroCurvatureIsExactLine() throws {
        let s = try SpiralSegment(start: .init(x: 1000, y: 2000), length: 100, startHeading: .pi / 4, startCurvature: 0, endCurvature: 0)
        TestSupport.assertPoint(s.end, 1000 + 100 / sqrt(2), 2000 + 100 / sqrt(2))
    }
    func testConstantCurvatureMatchesCircle() throws {
        let s = try SpiralSegment(start: .init(x: 0, y: 0), length: 100, startHeading: 0, startCurvature: 0.005, endCurvature: 0.005)
        TestSupport.assertPoint(s.end, 200 * sin(0.5), 200 * (1 - cos(0.5)), accuracy: 1e-10)
    }
    func testLeftRightProjection() throws {
        let s = try TestSupport.spiral()
        for offset in [-25.0, -5, 0, 5, 25] {
            let p = try s.point(at: 50); let q = OffsetEngine.coordinate(centerline: p, tangent: s.tangent(at: 50), offset: offset)
            let nearest = try s.closestPoint(to: q)
            XCTAssertEqual(nearest.distanceAlong, 50, accuracy: 1e-6)
            XCTAssertEqual(OffsetEngine.signedOffset(tangent: nearest.tangent, from: nearest.point, to: q), offset, accuracy: 1e-6)
        }
    }
    func testEndpointProjection() throws {
        let s = try TestSupport.spiral()
        XCTAssertEqual(try s.closestPoint(to: .init(x: -5, y: 0)).distanceAlong, 0, accuracy: 1e-8)
        let beyond = GeometryUtilities.translated(s.end, by: s.tangent(at: 100), scale: 5)
        XCTAssertEqual(try s.closestPoint(to: beyond).distanceAlong, 100, accuracy: 1e-7)
    }
    func testEndpointMismatchRejected() {
        XCTAssertThrowsError(try SpiralSegment(start: .init(x: 0, y: 0), length: 100, startHeading: 0, startCurvature: 0, endCurvature: 0.005, declaredEnd: .init(x: 100, y: 0)))
    }
    func testInvalidParametersRejected() {
        XCTAssertThrowsError(try SpiralSegment(start: .init(x: 0, y: 0), length: 0, startHeading: 0, startCurvature: 0, endCurvature: 0.005))
        XCTAssertThrowsError(try SpiralSegment(start: .init(x: 0, y: 0), length: 100, startHeading: .nan, startCurvature: 0, endCurvature: 0.005))
    }
    func testClosestSearchAgainstDenseIndependentReference() throws {
        let s = try TestSupport.spiral(decreasing: true)
        for q in [ProjectCoordinate(x: 35, y: 40), .init(x: 85, y: -60), .init(x: -20, y: 15)] {
            let r = try s.closestPoint(to: q)
            var denseBest = Double.infinity
            for i in 0...5000 { denseBest = min(denseBest, try s.point(at: Double(i) / 50).distance(to: q)) }
            XCTAssertLessThanOrEqual(r.queryDistance, denseBest + 1e-7)
        }
    }
}
