import XCTest
import RoadStationCore
import Projections
import proj
@testable import RoadStationAppleCRS

final class PROJTransformerTests: XCTestCase {
    private func transformer(_ code: Int, _ unit: CoordinateUnit = .linear(.meter)) throws -> PROJProjectCoordinateTransformer {
        try PROJProjectCoordinateTransformer(resolution: .identified(CoordinateReferenceSystem(epsgCode: code)), outputUnit: unit)
    }

    func testInstalledSwiftModulesAndNGABundledDatabase() {
        // Compile-time verification of the actual Swift-imported NGA API and C module.
        XCTAssertTrue(FileManager.default.fileExists(atPath: PROJIOUtils.databasePath()))
        XCTAssertEqual(proj_info().major, 9)
        XCTAssertEqual(proj_info().minor, 4)
    }

    func testUnresolvedReadinessAndInitialization() {
        let resolution = CRSResolution.unresolved(.missingIdentification)
        XCTAssertEqual(PROJProjectCoordinateTransformer.readiness(resolution: resolution, outputUnit: .linear(.meter)),
                       .unresolved(.missingIdentification))
        XCTAssertThrowsError(try PROJProjectCoordinateTransformer(resolution: resolution, outputUnit: .linear(.meter))) {
            XCTAssertEqual($0 as? CoordinateTransformationError, .unresolvedCRS(.missingIdentification))
        }
    }

    func testUnknownEPSGAndNonHorizontalCRSAreTypedFailures() throws {
        for code in [999999, 4978, 4979, 5703] {
            XCTAssertThrowsError(try transformer(code)) {
                XCTAssertEqual($0 as? CoordinateTransformationError, .unsupportedCRS("EPSG:\(code)"))
            }
        }
        let result = PROJProjectCoordinateTransformer.readiness(
            resolution: .identified(try CoordinateReferenceSystem(epsgCode: 999999)), outputUnit: .linear(.meter))
        XCTAssertEqual(result, .unavailable(.unsupportedCRS("EPSG:999999")))
    }

    func testEPSG4326IdentityIsExplicitLongitudeLatitudeDegrees() throws {
        let t = try transformer(4326, .degree)
        let input = try GeographicCoordinate(latitude: 32.4, longitude: -89.2)
        let point = try t.projectCoordinate(from: input)
        XCTAssertEqual(point.x, -89.2, accuracy: 1e-12)
        XCTAssertEqual(point.y, 32.4, accuracy: 1e-12)
        XCTAssertEqual(try t.geographicCoordinate(from: point), input)
        XCTAssertNil(point.z)
        XCTAssertEqual(t.definition.nativeUnit, .degree)
        XCTAssertThrowsError(try transformer(4326, .linear(.meter)))
        XCTAssertThrowsError(try t.geographicCoordinate(from: ProjectCoordinate(x: 181, y: 0)))
        XCTAssertThrowsError(try t.geographicCoordinate(from: ProjectCoordinate(x: 0, y: 91)))
    }

    func testIndependentNGAPublishedWebMercatorReferenceForwardAndInverse() throws {
        // Fixed values published by NGA, never generated by RoadStation:
        // https://github.com/ngageoint/projections-ios/blob/3.0.0/proj-iosTests-swift/PROJSwiftReadmeTest.swift
        let t = try transformer(3857)
        let known = ProjectCoordinate(x: 111319.49079327357, y: 111325.14286638486)
        let point = try t.projectCoordinate(latitude: 1, longitude: 1)
        XCTAssertEqual(point.x, known.x, accuracy: 1e-7)
        XCTAssertEqual(point.y, known.y, accuracy: 1e-7)
        let inverse = try t.geographicCoordinate(from: known)
        XCTAssertEqual(inverse.latitude, 1, accuracy: 1e-12)
        XCTAssertEqual(inverse.longitude, 1, accuracy: 1e-12)
    }

    func testIndependentPROJPublishedUTMReferenceWithAsymmetricAxes() throws {
        // OSGeo's fixed GRS80 zone-32 reference at 12E,55N (equivalent to ETRS89
        // EPSG:25832 for this horizontal projection; WGS84/ETRS89 operation accuracy
        // is not a survey accuracy claim). Reference is external to RoadStation:
        // https://github.com/OSGeo/PROJ/blob/9.4.1/test/gie/more_builtins.gie
        let t = try transformer(25832)
        let point = try t.projectCoordinate(latitude: 55, longitude: 12)
        XCTAssertEqual(point.x, 691875.63214, accuracy: 0.001)
        XCTAssertEqual(point.y, 6098907.82501, accuracy: 0.001)
        let inverse = try t.geographicCoordinate(from: ProjectCoordinate(x: 691875.63214, y: 6098907.82501))
        XCTAssertEqual(inverse.latitude, 55, accuracy: 1e-8)
        XCTAssertEqual(inverse.longitude, 12, accuracy: 1e-8)
    }

    func testProjectedNorthEastAuthorityAxesAreNormalized() throws {
        // EPSG:3035 declares Northing then Easting. Its natural origin is 52N,10E.
        let context = try XCTUnwrap(proj_context_create())
        defer { proj_context_destroy(context) }
        XCTAssertNotEqual(proj_context_set_database_path(context, PROJIOUtils.databasePath(), nil, nil), 0)
        let native = try XCTUnwrap(proj_create(context, "EPSG:3035"))
        defer { proj_destroy(native) }
        let cs = try XCTUnwrap(proj_crs_get_coordinate_system(context, native))
        defer { proj_destroy(cs) }
        for (index, expected) in [(Int32(0), "north"), (Int32(1), "east")] {
            var direction: UnsafePointer<CChar>?
            XCTAssertNotEqual(proj_cs_get_axis_info(context, cs, index, nil, nil, &direction, nil, nil, nil, nil), 0)
            XCTAssertEqual(String(cString: try XCTUnwrap(direction)), expected)
        }
        let t = try transformer(3035)
        let point = try t.projectCoordinate(latitude: 52, longitude: 10)
        XCTAssertEqual(point.x, 4321000, accuracy: 0.001)
        XCTAssertEqual(point.y, 3210000, accuracy: 0.001)
        let inverse = try t.geographicCoordinate(from: point)
        XCTAssertEqual(inverse.latitude, 52, accuracy: 1e-8)
        XCTAssertEqual(inverse.longitude, 10, accuracy: 1e-8)
    }

    func testForwardInverseRoundTripsAcrossMultipleEPSGsAndUnits() throws {
        for (code, latitude, longitude) in [(32632, 55.0, 12.0), (32756, -33.0, 151.0), (3857, 32.4, -89.2)] {
            for unit in [ProjectUnit.meter, .internationalFoot, .usSurveyFoot] {
                let t = try transformer(code, .linear(unit))
                let input = try GeographicCoordinate(latitude: latitude, longitude: longitude)
                let result = try t.geographicCoordinate(from: t.projectCoordinate(from: input))
                XCTAssertEqual(result.latitude, latitude, accuracy: 1e-9)
                XCTAssertEqual(result.longitude, longitude, accuracy: 1e-9)
            }
        }
    }

    func testNativeEPSGUnitsAndExplicitOutputConversion() throws {
        for (code, nativeUnit, latitude, longitude) in [
            (2222, ProjectUnit.internationalFoot, 33.0, -110.0),
            (2276, ProjectUnit.usSurveyFoot, 33.0, -97.0),
            (32632, ProjectUnit.meter, 55.0, 12.0)
        ] {
            let native = try transformer(code, .linear(nativeUnit))
            XCTAssertEqual(native.definition.nativeUnit, .linear(nativeUnit))
            let nativePoint = try native.projectCoordinate(latitude: latitude, longitude: longitude)
            for outputUnit in [ProjectUnit.meter, .internationalFoot, .usSurveyFoot] {
                let t = try transformer(code, .linear(outputUnit))
                let point = try t.projectCoordinate(latitude: latitude, longitude: longitude)
                let factor = nativeUnit.metersPerUnit! / outputUnit.metersPerUnit!
                XCTAssertEqual(point.x, nativePoint.x * factor, accuracy: 1e-6)
                XCTAssertEqual(point.y, nativePoint.y * factor, accuracy: 1e-6)
                let inverse = try t.geographicCoordinate(from: point)
                XCTAssertEqual(inverse.latitude, latitude, accuracy: 1e-7)
                XCTAssertEqual(inverse.longitude, longitude, accuracy: 1e-7)
            }
        }
        let international = try transformer(3857, .linear(.internationalFoot)).projectCoordinate(latitude: 32, longitude: -89)
        let survey = try transformer(3857, .linear(.usSurveyFoot)).projectCoordinate(latitude: 32, longitude: -89)
        XCTAssertGreaterThan(abs(international.x - survey.x), 60)
    }

    func testInvalidUnknownAndIncompatibleUnits() {
        XCTAssertThrowsError(try transformer(3857, .degree))
        XCTAssertThrowsError(try transformer(3857, .linear(.unknown))) {
            XCTAssertEqual($0 as? CoordinateTransformationError, .unsupportedUnits)
        }
    }

    func testNonFiniteProjectValuesHeightAndOverflowAreRejected() throws {
        let t = try transformer(3857)
        for value in [Double.nan, .infinity, -.infinity] {
            for point in [ProjectCoordinate(x: value, y: 1), ProjectCoordinate(x: 1, y: value),
                          ProjectCoordinate(x: 1, y: 1, z: value)] {
                XCTAssertThrowsError(try t.geographicCoordinate(from: point)) {
                    XCTAssertEqual($0 as? CoordinateTransformationError, .nonFiniteCoordinate)
                }
            }
        }
        XCTAssertThrowsError(try t.geographicCoordinate(from: ProjectCoordinate(x: 1, y: 2, z: 3))) {
            XCTAssertEqual($0 as? CoordinateTransformationError, .unexpectedHeight)
        }
        let feet = try transformer(3857, .linear(.usSurveyFoot))
        XCTAssertThrowsError(try feet.geographicCoordinate(from: ProjectCoordinate(x: .greatestFiniteMagnitude, y: .greatestFiniteMagnitude)))
    }

    func testProjectionDomainFailureDoesNotReturnInvalidCoordinate() throws {
        let t = try transformer(32632)
        XCTAssertThrowsError(try t.projectCoordinate(latitude: 0, longitude: 99))
    }
}
